### ISSUE TITLE
Basic a11y check

### ISSUE THREAD

**Issue by sushilburagute** [neogcamp/platform-93by4#11]
# Basic Check for Accessibility
---

- Contrast Check.
- Images should have `alt` attribute.
- Semantic HTML .
- Navigating the UI using the keyboard.

Refer: 

https://developer.mozilla.org/en-US/docs/Web/Accessibility
https://www.w3.org/WAI/test-evaluate/preliminary/

**Comment by uditkumar01** [comment]
I think Eslint is enforcing a11y checks [plugin:jsx-a11y/recommended](https://github.com/neogcamp/platform-93by4/blob/eb611a116a02c1b3101b5831428978f042cd1e73/.eslintrc.js#L31),
