### ISSUE TITLE
Proposed: Link logo change on Student dashboard. 

### ISSUE THREAD

**Issue by MehulKChaudhari** [neogcamp/platform-93by4#123]
The logo on the dashboard for Submit your portfolio states it is an external link while it's not,
![Screenshot from 2021-07-30 09-30-00](https://user-images.githubusercontent.com/55375534/127598686-ab2ba057-50d3-447d-a4c3-5d558e05ec51.png)
So I believe we need to change the logo to the logo in the picture below.
![Screenshot from 2021-07-30 09-30-23](https://user-images.githubusercontent.com/55375534/127598724-eae9198a-7fe5-43c5-b653-77e01d4c265b.png)
.

**Comment by MehulKChaudhari** [comment]
Hey @sushilburagute, I hope this makes sense to you as well?

**Comment by MehulKChaudhari** [comment]
@NadaaFarook Can you please look into this issue? It will harding take 5 minutes.

**Comment by sushilburagute** [comment]
Yup. Let's go ahead with this change. It would make things clear.
