### ISSUE TITLE
CheckMarks on the `submissions/checklist` page behaves weird on check-uncheck actions

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/platform-93by4#127]
Steps to reproduce:
- GO on `/submissions/checklist` page
- Try to tick all the tasks of markOne (or any of the marks)
- Once you click on tick for 3rd task, expected behavior is to change the SVG of circle to tick.
- But in between there is a delay observed, where src is undefined and thus alt text is shown for half milisecond.

Also, when going to next page and then returning or vice-versa; this behavior was observed.

This should be a quick fix. Would need refactoring. But priority is to know the reason of problem. Work-arounds can also solve this.

### Broken State
![image](https://user-images.githubusercontent.com/47717492/128297605-379513fe-3957-4797-aad3-fb24b1320916.png)

@uditkumar01 Can you help out in this?

**Comment by NadaaFarook** [comment]
Even there is delay on the dashboard image

**Comment by sushilburagute** [comment]
Solution: Move the icons we're using from the `src` folder, to the `react-icons` package

**Comment by uditkumar01** [comment]
It's fixed now by @sushilburagute
