### ISSUE TITLE
Login/Sign Up page loading issue

### ISSUE THREAD

**Issue by shaivik** [neogcamp/platform-93by4#140]
### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Describe the Bug

Login page resizing on load. 

[https://drive.google.com/file/d/18k2jtO_hBiXnMjMUTL75yDAc2pY59uhL/view?usp=sharing](url)

### Expected Behavior

Shouldn't resize or we could introduce some CSS transitions to make it look better. 

### To Reproduce

Throttle the network speed and try reloading the page. 
https://admissions.neog.camp/auth/login

**Comment by OmkarK45** [comment]
Hi Shivam! Thanks for reporting this issue. I will look into it 👍
