### ISSUE TITLE
Dashboard button redundancy 

### ISSUE THREAD

**Issue by shaivik** [neogcamp/platform-93by4#141]
### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Describe the Bug

- Dashboard button is redundant and seems to be of no use. 

- Also the redirection to dashboard page after showing the landing page seems to be odd. Redirection logic should be written before rendering takes place. 

[Image](https://drive.google.com/file/d/14NEVgJtTFKip2w5yb_jHsNTR6H69wvgF/view?usp=sharing)

### Expected Behavior

- Dashboard button can be removed.
- Landing page shouldn't be rendered.

### To Reproduce

- Dashboard button could be replaced by profile button where user details could be changed.
- Login and then close the platform page. Reopening it again would lead to redirection issue. First the landing page is shown and then the user is redirected to dashboard page.

**Comment by MehulKChaudhari** [comment]
Thank you for report, Looking into it.
