### ISSUE TITLE
Submission URL should start with https:// always

### ISSUE THREAD

**Issue by MehulKChaudhari** [neogcamp/platform-93by4#147]
### Describe the Bug

For now your submission algorithm treats `adarshbalika.com` and `https://adarshbalika.com` as two different URL's. But they are same So we have to figure out how to resolve this. 

### Expected Behavior

`adarshbalika.com` and `https://adarshbalika.com` should be treated as one URL

### To Reproduce

we have one option to resolve this issue is to make https:// as default

**Comment by Tanviprya** [comment]
TBD for Phase 1. (later iteration)
