### ISSUE TITLE
Forgot Password - show password button

### ISSUE THREAD

**Issue by sneha-pujari** [neogcamp/platform-93by4#149]
### Describe the Bug

- Under Forgot Password, the option to show password can be added for the 'Confirm Password' input field.

![image](https://user-images.githubusercontent.com/58720128/128971002-faafe0ed-4fb5-42c6-923a-07c63ee8f44f.png)

### Expected Behavior

- Show Password button should be available for both the input fields - 'New Password' and 'Confirm New Password' but was available only for 'New Password' input field. 

### To Reproduce

- Show Password option can be added in both 'New Password' and 'Confirm New Password'.
- It could also be a common button for both the fields. 

![image](https://user-images.githubusercontent.com/58720128/128970516-f567f180-8d7a-4092-9e63-638f0edf82b8.png)

**Comment by MehulKChaudhari** [comment]
Thank you report, Looking into it.
