### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/platform-93by4#16]
A License is essential for our project since it is public at the moment and also if we are intending to extend this to allow more contributors to help with the project and also potentially use it, licensing is important to boundary the usage of the codebase.

[This](https://opensource.org/licenses) is a good guide upon which license would fit our project best.

**Comment by uditkumar01** [comment]
Hi, @sohamsshah, `LICENCE.md` is initialized [here](https://github.com/neogcamp/platform-93by4/tree/add-license). I am closing this issue for now. If u think we need to improve it or change it plz either mention it in [Final Issues](https://github.com/neogcamp/platform-93by4/issues/45) or create new issue.
