### ISSUE TITLE
Email API for sending Emails 

### ISSUE THREAD

**Issue by OmkarK45** [neogcamp/platform-93by4#41]
We are currently using mailtrap (which cannot be used in production ofcourse)

We will need some sort of API which can provide emails over SMTP protocol. 

Something like Mailchimp or SendGrid would suffice.

**Comment by uditkumar01** [comment]
Hi @OmkarK45 , please mention this issue in [Final Issues](https://github.com/neogcamp/platform-93by4/issues/45) if not mentioned. As it is `one issue for all major issues`.
