### ISSUE TITLE
Authentication UI and Logic Bugs

### ISSUE THREAD

**Issue by prerana1821** [neogcamp/platform-93by4#61]
# Student Authentication Flow Bug bash
1. if reset confirm password validation field is empty, user should not be able to submit new password
   - even if I'm not adding confirm password I can submit & password can be changed.
  
    ![Screenshot 2021-07-07 180322](https://user-images.githubusercontent.com/61601706/124759784-aa71e980-df4d-11eb-8103-d7c0af0773d7.png)

2. email field validation issue
    - I guess this should be considered as a invalid email id
  
   ![Screenshot 2021-07-07 180548](https://user-images.githubusercontent.com/61601706/124760071-fd4ba100-df4d-11eb-94ec-45ba45205416.png)
    
3. delete `neogSubmission` details from localstorage when user will logout
    - when user is logged out `neogSubmission` is still present in local storage
    
    ![image](https://user-images.githubusercontent.com/61601706/124760191-1d7b6000-df4e-11eb-8a94-8271a3033bdb.png)
  

4. userDetails api call should only happen if token exists

   
   ![image](https://user-images.githubusercontent.com/61601706/124760527-7519cb80-df4e-11eb-88e3-17ac2be7bfd2.png)

6. Student can not see any other pages if not signed in (protection)
   - if I logout from submission-checklist, logout redirects to submission-checklist itself
   -  if token exists user should not be able to go to the login page

7. resend verification link
    - if I click on `resend verification link` it shows `couldn't send email`
   
    ![image](https://user-images.githubusercontent.com/61601706/124761119-143ec300-df4f-11eb-810f-58ada5a42053.png)

8. login page password validation not working
9. toast message for email already exits while login if user puts same already existing email 
10. sign up user email should case insensitivity
    - eg. `hello@gmail.com` & `Hello@gmail.com` should be considered as same
11. remove previous verification window once user is logged in
12. last name should be 2 character's long

## UI Changes -

1. have to change image placeholder for login & signup page
2. neogcamp logo should have cursor pointer
3. on selection background color changes to white
4. Email verification card can be aligned

![image](https://user-images.githubusercontent.com/61601706/124760728-a6929700-df4e-11eb-8d53-f5a4f4040fc7.png)

**Comment by sohamsshah** [comment]
Is this issue solved? @OmkarK45

**Comment by OmkarK45** [comment]
> Is this issue solved? @OmkarK45

Yes

**Comment by sohamsshah** [comment]
Closing this via #66
