### ISSUE TITLE
Submission & Resubmission Bugs

### ISSUE THREAD

**Issue by prerana1821** [neogcamp/platform-93by4#71]
## Submission & resubmission window bug bash
1. When I submit the portfolio URL, it redirects to congrats card page but the submission Id & current status is not visible it comes after page refresh.
    ![image](https://user-images.githubusercontent.com/61601706/125043320-72d38080-e0b8-11eb-8c69-5634932bd2e8.png)
2. "**Go back to Dashboard**" button redirects to landing page.
3. When I submit the same URL previously submitted by the another url it gives me warning that it is already submitted but also redirects to the congrats card which should not happen.
4.  When I resubmit the portfolio link from resubmission window its not updating in the DB
5. Submission number auto-incrementation not working properly.

**Comment by NadaaFarook** [comment]
6. When a portfolio is assigned to be needs revision . The current status of the student will be "portfolio_needs_revision" . But once a student submits the portfolio again . The current status is not changing to "under_review" again.

**Comment by MehulKChaudhari** [comment]
> 1. When a portfolio is assigned to be needs revision . The current status of the student will be "portfolio_needs_revision" . But once a student submits the portfolio again . The current status is not changing to "under_review" again.

**Comment by MehulKChaudhari** [comment]
@NadaaFarook Could you please elaborate

**Comment by MehulKChaudhari** [comment]
@NadaaFarook  As of now, it's never changed to `needs revision`. and please let me know in what conditions it's not getting updated? because when last me I checked, It works fine

**Comment by MehulKChaudhari** [comment]
@prerana1821 
1. Working on it. 
2. Fixed it.
3. oh will be doing it. 
4. It works fine please check once again and let me know if behaves that way this time too.
5. same as above.

**Comment by MehulKChaudhari** [comment]
Bugs are fixed and merged into develop.
