### ISSUE TITLE
When user is logged in then login/signup button shouldn't be on landing page

### ISSUE THREAD

**Issue by uditkumar01** [neogcamp/platform-93by4#79]
![Screenshot 2021-07-12 at 11-39-48 NeoG Camp Admission Portal](https://user-images.githubusercontent.com/55291327/125239176-e7e7c580-e305-11eb-96d9-53ae75f481cd.png)

**Comment by sohamsshah** [comment]
I think we should not let the user access the `/` route in the first place and redirect directly to `/dashboard` because on landing page we don't have anything specific.

Alternatively, on landing page we can have `Go to Dashboard` Button instead of Login and Signup.

**Comment by sushilburagute** [comment]
Ah valid point. The SaaS Product I've seen route the user to the dashboard if they're signed in. I'll work on this after tomorrow's code review.

**Comment by uditkumar01** [comment]
> I think we should not let the user access the `/` route in the first place and redirect directly to `/dashboard` because on landing page we don't have anything specific.
> 
> Alternatively, on landing page we can have `Go to Dashboard` Button instead of Login and Signup.

**Comment by sushilburagute** [comment]
Bug resolved!
