### ISSUE TITLE
Email didn't receive on Mailtrap

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/platform-93by4#89]
Not sure if this is a reproducible bug but for multiple instances have seen that email isn't been sent to mailtrap inbox.
Even on clicking on some other account's `email verification button` in the email body, my present account got verified which was a bit weird behavior.

![image](https://user-images.githubusercontent.com/47717492/125290559-12557500-e33e-11eb-989e-c724ee87215b.png)

**Comment by OmkarK45** [comment]
Closing this as this has been fixed
