### ISSUE TITLE
Unexpected page view on `/submission` page

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/platform-93by4#90]
![Screenshot (26)](https://user-images.githubusercontent.com/47717492/125290724-416be680-e33e-11eb-8a7f-a10e7e605e2d.png)
![Screenshot (25)](https://user-images.githubusercontent.com/47717492/125290732-4335aa00-e33e-11eb-8844-5d8ebcdc5dd7.png)

How to Reproduce:
- Go to `/submission`
- See broken view

This is majorly because of incorrect syntax. Must be a quick fix but has to be handled properly because there are multiple components depending upon this page.

https://github.com/neogcamp/platform-93by4/blob/0976729a1d8be10a7a6055f284a03654eed9c3e9/client/src/pages/submission/index.tsx#L198-L201

@MehulKChaudhari Please check this out.

**Comment by MehulKChaudhari** [comment]
checking into

**Comment by MehulKChaudhari** [comment]
Done check PR #93

**Comment by sohamsshah** [comment]
Closed via #93
