### ISSUE TITLE
Cannot access `/resubmission` page even when the status is `portfolio_needs_revision`

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/platform-93by4#91]
When the status of user is changed to `portfolio_needs_revision` it is expected to let the user access `/resubmission` and protect the `/submission` route instead.

**Comment by MehulKChaudhari** [comment]
because it's not set to `needs revision` in context from the dashboard, please check with the dashboard person.

**Comment by sohamsshah** [comment]
^@NadaaFarook
