### ISSUE TITLE
`status` doesn't change on resubmission in database

### ISSUE THREAD

**Issue by sohamsshah** [neogcamp/platform-93by4#92]
When the user resubmits the portfolio, the following actions must happen in the database:
- Update the Portfolio URL
- Update Submission Number
- Update Status from `portfolio_needs_revision` to `portfolio_under_review`

Presently, in the backend, the status isn't updated and thus might cause issues in the future during resubmission steps.

**Comment by MehulKChaudhari** [comment]
Fixed
