### ISSUE TITLE
Error on occurring on dashboard.

### ISSUE THREAD

**Issue by MehulKChaudhari** [neogcamp/platform-93by4#95]
![Screenshot from 2021-07-13 12-50-20](https://user-images.githubusercontent.com/55375534/125409169-42058b00-e3d9-11eb-9504-6beaf490aa8b.png)

**Comment by NadaaFarook** [comment]
Can you share more details how this bug was encountered ?

**Comment by uditkumar01** [comment]
I think @NadaaFarook the initial state of `state` doesn't have the `state` property so that is why it was breaking while going to `resubmission` route.

**Comment by MehulKChaudhari** [comment]
> Can you share more details how this bug was encountered ?

When the user logins we get this error.
